#let red    = rgb("#fb4934")
#let green  = rgb("#b8bb26")
#let yellow = rgb("#fabd2f")
#let blue   = rgb("#83a598")
#let purple = rgb("#d3869b")
#let aqua   = rgb("#8ec07c")
#let gray   = rgb("#928374")
#let orange = rgb("#fe8019")

#let red_dim    = rgb("#cc2412")
#let green_dim  = rgb("#98971a")
#let yellow_dim = rgb("#d79921")
#let blue_dim   = rgb("#458588")
#let purple_dim = rgb("#b16286")
#let aqua_dim   = rgb("#689d6a")
#let gray_dim   = rgb("#a89984")
#let orange_dim = rgb("#d65d0e")

#let fg0 = rgb("#fbf1c7")
#let fg1 = rgb("#ebdbb2")
#let fg2 = rgb("#d5c4a1")
#let fg3 = rgb("#bdae93")
#let fg4 = rgb("#a89984")

#let bg0 = rgb("#282828")
#let bg1 = rgb("#3c3836")
#let bg2 = rgb("#504945")
#let bg3 = rgb("#665c54")
#let bg4 = rgb("#7c6f64")

#let tred(body)        = text(fill: rgb("#fb4934"), body)
#let tgreen(body)      = text(fill: rgb("#b8bb26"), body)
#let tyellow(body)     = text(fill: rgb("#fabd2f"), body)
#let tblue(body)       = text(fill: rgb("#83a598"), body)
#let tpurple(body)     = text(fill: rgb("#d3869b"), body)
#let taqua(body)       = text(fill: rgb("#8ec07c"), body)
#let tgray(body)       = text(fill: rgb("#928374"), body)
#let torange(body)     = text(fill: rgb("#fe8019"), body)

#let tred_dim(body)    = text(fill: rgb("#cc2412"), body)
#let tgreen_dim(body)  = text(fill: rgb("#98971a"), body)
#let tyellow_dim(body) = text(fill: rgb("#d79921"), body)
#let tblue_dim(body)   = text(fill: rgb("#458588"), body)
#let tpurple_dim(body) = text(fill: rgb("#b16286"), body)
#let taqua_dim(body)   = text(fill: rgb("#689d6a"), body)
#let tgray_dim(body)   = text(fill: rgb("#a89984"), body)
#let torange_dim(body) = text(fill: rgb("#d65d0e"), body)

#let twhite(body)      = text(fill: rgb("#fbf1c7"), body)

#let tiny(body)       = text(size: 15pt, body)
#let small(body)      = text(size: 20pt, body)
#let medium(body)     = text(size: 25pt, body)
#let large(body)      = text(size: 30pt, body)
#let huge(body)       = text(size: 40pt, body)

#let bold(body)       = text(weight: "bold", body)