@startuml img_source

title Kép forrás

class ImageSource {
    Mat original
    CachedImage cached
    int amount
    Filter[] filters
    
    bool rotated
    size_t width, height
    
    void add_filter(Filter filter)
    void clear_filters()
    void apply_filters()
    Mat get_img()
}

abstract Filter {
    Mat apply(Mat img)
}
ImageSource *-- Filter


class Mask {
    Mat mask
    Mat apply(Mat img)
}
Filter <|-- Mask

class Size {
    int width
    int height
    Mat apply(Mat img)
}
Filter <|-- Size

class Padding {
    int padding
    Mat apply(Mat img)
}
Filter <|-- Padding

class Rotate {
    bool rotate
    Mat apply(Mat img)
}
Filter <|-- Rotate

class Tile {
    ImageSource image
    Point corner
    bool rotated
}
ImageSource -* Tile

class CachedImage {
    ICachableImage source
    Mat cache
    bool dirty
}
CachedImage *- ImageSource


interface ICache {
    void set_dirty()
}

interface ICachableImage {
    Mat get_cachable()
}

ICache <|-- CachedImage
ICachableImage <|-- ImageSource

@enduml