@startuml pdf_source_view

title PDF forrás nézet


class ImageSourceView {
    get_imagesource(): ImageSource
    load_from_json(json)
    propbe_presets(): map<string, string>
}

class PDFSourceView {
    get_imagesource(): ImageSource
}
ImageSourceView <|-- PDFSourceView



@enduml