@startuml presets

title Beállítások

class SourcePreset {
    std::string name
    size_t width, height
    std::vector<Filter> filters
}

class DocumentPreset {
    std::string name
    double ppi
    double roll_width_mm
    double margin_mm
    double gutter_mm
    double min_height_mm
    double max_height_mm

    size_t document_width_px
    size_t gutter_px
    bool guidelines
}


@enduml