@startuml tiling

title Csempézés

interface Tiling {
    generate(preset: DocumentPreset, images: [ImageSource]): Mat
}

class GridTiling {
    generate(...): Mat
}
Tiling <|-- GridTiling

class StripTiling {
    generate(...): Mat
}
Tiling <|-- StripTiling

@enduml