@startuml tiling

title Csempézés

interface Tiling {
    cv::Mat generate(DocumentPreset preset, std::vector<ImgSource> images)
}

class GridTiling {
    cv::Mat generate(...)
}
Tiling <|-- GridTiling

class StripTiling {
    cv::Mat generate(...)
}
Tiling <|-- StripTiling

@enduml