@startuml ui

title UI

entity Application {
}


class SourceEntryView {
    void remove(index)
    void addFiles(files)
    void clear()
}
Application *- SourceEntryView

class ImageSourceView {
    ImageSource get_imagesource()
    void load_from_json(json)
    map<string, string> propbe_presets()
}
SourceEntryView *-- "*" ImageSourceView

abstract FilterView {
    Filter get_filter()
    void load_from_json(json)
}
ImageSourceView *-- "*" FilterView

class MaskView {
}
FilterView <|-- MaskView

class RotateView {
}
FilterView <|-- RotateView

class SizeView {
}
FilterView <|-- SizeView


class DocumentPropertiesView {
    DocumentProperties get_properties()
    void load_from_json(json)
    map<string, string> propbe_presets()
}
DocumentPropertiesView --* Application


class ControlView {
    void generate()
    void save()
    void print()
}
ControlView -* Application

class Preview{
    void set_image(cv::Mat)
}
Preview --* Application


abstract Tiling {
    cv::Mat generate(...)
}
ControlView --> Tiling

@enduml