@startuml ui

title UI

entity Application {
}


class SourceEntryView {
    remove(index)
    addFiles(files)
    clear()
}
Application *- SourceEntryView

class ImageSourceView {
    get_imagesource(): ImageSource
    load_from_json(json)
    propbe_presets(): map<string, string>
}
SourceEntryView *-- "*" ImageSourceView

interface FilterView {
    get_filter(): Filter
    load_from_json(json)
    propbe_presets(): map<string, string>
}
ImageSourceView *-- "*" FilterView

class MaskView {
}
FilterView <|-- MaskView

class RotateView {
}
FilterView <|-- RotateView

class SizeView {
}
FilterView <|-- SizeView


class DocumentPropertiesView {
    get_properties(): DocumentProperties
    load_from_json(json)
    propbe_presets(): map<string, string>
}
DocumentPropertiesView --* Application


class ControlView {
    generate()
    save()
}
ControlView -* Application

class Preview{
    set_image(Mat)
}
Preview --* Application


interface Tiling {
    generate(...): Mat
}
ControlView --> Tiling

@enduml