name: Build with Meson

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.cpp_compiler }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      
      matrix:
        os: [ubuntu-latest]
        cpp_compiler: [g++, clang++]
        build_type: [Release]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install meson and ninja
        run: sudo apt install -y --no-install-recommends meson ninja-build
      - name: Get dependencies
        run: sudo apt install -y --no-install-recommends libopencv-dev qt6-base-dev nlohmann-json3-dev libcups2-dev
      - name: Configure Project
        run: meson setup build
      - name: Build Project
        run: cd build && meson compile
        env:
          CC: ${{ matrix.cpp_compiler }}
