name: Build with Meson

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v1.7.0
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      
      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install meson and ninja
        run: sudo apt install -y meson ninja-build
      - name: Get opencv
        run: sudo apt install -y libopencv-dev
      - name: Get QT6
        run: sudo apt install -y qt6-base-dev
      - name: Get nlohman_json
        run: meson wrap install nlohmann_json
      - name: Configure Project
        run: meson setup build
        env:
          CC: ${{ matrix.cpp_compiler }}
      - name: Build Project
        run: ninja -C build
        env:
          CC: ${{ matrix.cpp_compiler }}
